
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.monster
{
public partial class Tbmonster
{
    private readonly System.Collections.Generic.Dictionary<string, monster.Monster> _dataMap;
    private readonly System.Collections.Generic.List<monster.Monster> _dataList;
    
    public Tbmonster(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, monster.Monster>();
        _dataList = new System.Collections.Generic.List<monster.Monster>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            monster.Monster _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = monster.Monster.DeserializeMonster(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, monster.Monster> DataMap => _dataMap;
    public System.Collections.Generic.List<monster.Monster> DataList => _dataList;

    public monster.Monster GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public monster.Monster Get(string key) => _dataMap[key];
    public monster.Monster this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

