
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbTest TbTest {get; }
    public TbtestA TbtestA {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbTest = new TbTest(loader("tbtest"));
        TbtestA = new TbtestA(loader("tbtesta"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbTest.ResolveRef(this);
        TbtestA.ResolveRef(this);
    }
}

}
