
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.item
{ 
    public enum EType
    {
        物品 = 0,
        寶物 = 1,
        武器 = 2,
        防具 = 3,
    }

} 

