
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.item
{
public sealed partial class Item : Luban.BeanBase
{
    public Item(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (item.EType)_buf["type"].AsInt; }
        { if(!_buf["use_type"].IsNumber) { throw new SerializationException(); }  UseType = (item.EUseType)_buf["use_type"].AsInt; }
        { var __json0 = _buf["properties"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Properties = new PropertyData[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { PropertyData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = PropertyData.DeserializePropertyData(__e0);  }  Properties[__index0++] = __v0; }   }
        { var __json0 = _buf["percent_properties"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; PercentProperties = new PercentPropertyData[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { PercentPropertyData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = PercentPropertyData.DeserializePercentPropertyData(__e0);  }  PercentProperties[__index0++] = __v0; }   }
        { var __json0 = _buf["items"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Items = new ItemData[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { ItemData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemData.DeserializeItemData(__e0);  }  Items[__index0++] = __v0; }   }
        { if(!_buf["system"].IsString) { throw new SerializationException(); }  System = _buf["system"]; }
        { if(!_buf["pick_tips"].IsString) { throw new SerializationException(); }  PickTips = _buf["pick_tips"]; }
        { if(!_buf["use_tips"].IsString) { throw new SerializationException(); }  UseTips = _buf["use_tips"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
    }

    public static Item DeserializeItem(JSONNode _buf)
    {
        return new item.Item(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 圖標
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 類型
    /// </summary>
    public readonly item.EType Type;
    /// <summary>
    /// 使用類型
    /// </summary>
    public readonly item.EUseType UseType;
    /// <summary>
    /// type
    /// </summary>
    public readonly PropertyData[] Properties;
    /// <summary>
    /// type
    /// </summary>
    public readonly PercentPropertyData[] PercentProperties;
    /// <summary>
    /// id
    /// </summary>
    public readonly ItemData[] Items;
    /// <summary>
    /// 系統
    /// </summary>
    public readonly string System;
    /// <summary>
    /// 拾取提示
    /// </summary>
    public readonly string PickTips;
    /// <summary>
    /// 使用提示
    /// </summary>
    public readonly string UseTips;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = 2107285806;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Properties) { _e?.ResolveRef(tables); }
        foreach (var _e in PercentProperties) { _e?.ResolveRef(tables); }
        foreach (var _e in Items) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "icon:" + Icon + ","
        + "type:" + Type + ","
        + "useType:" + UseType + ","
        + "properties:" + Luban.StringUtil.CollectionToString(Properties) + ","
        + "percentProperties:" + Luban.StringUtil.CollectionToString(PercentProperties) + ","
        + "items:" + Luban.StringUtil.CollectionToString(Items) + ","
        + "system:" + System + ","
        + "pickTips:" + PickTips + ","
        + "useTips:" + UseTips + ","
        + "desc:" + Desc + ","
        + "}";
    }
}

}

