
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ItemData : Luban.BeanBase
{
    public ItemData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        Id_Ref = null;
        { if(!_buf["count"].IsNumber) { throw new SerializationException(); }  Count = _buf["count"]; }
    }

    public static ItemData DeserializeItemData(JSONNode _buf)
    {
        return new ItemData(_buf);
    }

    /// <summary>
    /// 道具id
    /// </summary>
    public readonly string Id;
    public item.Item Id_Ref;
    /// <summary>
    /// 道具數量
    /// </summary>
    public readonly int Count;
   
    public const int __ID__ = 1241678205;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Id_Ref = tables.Tbitem.GetOrDefault(Id);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "count:" + Count + ","
        + "}";
    }
}

}

