
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public item.Tbitem Tbitem {get; }
    public monster.Tbmonster Tbmonster {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        Tbitem = new item.Tbitem(loader("item_tbitem"));
        Tbmonster = new monster.Tbmonster(loader("monster_tbmonster"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        Tbitem.ResolveRef(this);
        Tbmonster.ResolveRef(this);
    }
}

}
